### PR TITLE
Set track to active

### LINKED ISSUE #75: Prepare for launch
https://exercism.org/docs/building/tracks/new/prepare-for-launch

- [ ] add logos

### LINKED ISSUE #82: Launch!
Towards #1

### PR DESCRIPTION
**Pull request by misicnenad**
Closes #75, Closes #82

@ErikSchierboom @iHiD wasn't sure what does the launch process look exactly, so created this PR for you to approve once it _should_ be launched. Please let me know if I should contact somebody else regarding this.

I created a request to add Cairo logos, but they have not yet been added:
https://github.com/exercism/website-icons/issues/176
Does this preclude launching or can we launch regardless?

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I can't reopen a force-pushed PR, sorry

**Comment by ErikSchierboom** [comment]
> I created a request to add Cairo logos, but they have not yet been added:
> https://github.com/exercism/website-icons/issues/176
> Does this preclude launching or can we launch regardless?

I'd prefer to launch with the icon. @iHiD is this something you can do?

**Comment by misicnenad** [comment]
@ErikSchierboom my bad, I used rebase to update the branch instead of merge.

Opened a new PR https://github.com/exercism/cairo/pull/88

**Comment by ErikSchierboom** [comment]
Icon added and merged: https://github.com/exercism/website-icons/pull/177

**Comment by ErikSchierboom** [comment]
I've just added the track to the database, which means that maintainers (which includes you) can now access the track at https://exercism.org/tracks/cairo Before launching, I'd like some other maintainers to look at the track and test it. The way we usually do this is that you (the person that created the track) open a post on the forum (https://forum.exercism.org/) asking maintainers to help test the track.

That said, before doing that you should get a working test runner, which we require before launching a track. There is a repo, but it doesn't yet do anything: https://github.com/exercism/cairo-test-runner If you need help, let me know.

**Comment by misicnenad** [comment]
@ErikSchierboom opening the post and starting work on the test runner!

**Comment by ErikSchierboom** [comment]
Sorry, I think I might have explained it badly. What I would like to see is a separate PR to enable the test runner, which can then be merged without setting the track to active. This will allow maintainers to pre-test the track (and the test runner) before being launched.
The test runner will start working once https://github.com/exercism/terraform/pull/117 is merged, so you'll also have to wait for that.

**Comment by misicnenad** [comment]
@ErikSchierboom ah, now I understand. Removed test-runner changes from this PR and creating a new PR to just enable it.

**Comment by misicnenad** [comment]
@ErikSchierboom should a PR also be created for https://github.com/exercism/cli/blob/main/workspace/test_configurations.go#L63?

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom should a PR also be created for https://github.com/exercism/cli/blob/main/workspace/test_configurations.go#L63?

That would be great! 
And a snippet extractor PR: https://github.com/exercism/snippet-extractor
And a lines of code counter PR: https://github.com/exercism/lines-of-code-counter (which will also require a PR to https://github.com/exercism/tokei, like https://github.com/exercism/tokei/pull/17/files)

**Comment by misicnenad** [comment]
@ErikSchierboom created relevant PRs:
https://github.com/exercism/tokei/pull/18
https://github.com/exercism/lines-of-code-counter/pull/204
https://github.com/exercism/cli/pull/1151
https://github.com/exercism/snippet-extractor/pull/108 <-- this one you already merged

**Comment by ErikSchierboom** [comment]
The Cairo test runner has been deployed: https://github.com/exercism/cairo-test-runner/actions/runs/10057739306/job/27799348315
I don't remember if you did this, but I would recommend opening an issue on the Exercism forum requesting maintainers to try out the track (basically, getting feedback).

**Comment by misicnenad** [comment]
@ErikSchierboom yes I did http://forum.exercism.org/t/need-maintainers-to-test-the-new-cairo-track/12154

Not much interest though

**Comment by misicnenad** [comment]
@ErikSchierboom why is the track not yet available in the online editor? Is there something else I need to implement?
image

**Comment by misicnenad** [comment]
@ErikSchierboom do you know why there's no code highlight in the online editor?
image

It should be the same as Rust's, I set `"highlightjs_language": "rust"` in the [config.json](https://github.com/exercism/cairo/blob/main/config.json#L16).

**Comment by ErikSchierboom** [comment]
That's different, the online editor uses CodeMirror. Highlightjs is used for all non-interactive code snippets.

**Comment by misicnenad** [comment]
@ErikSchierboom are we good enough to launch?

**Comment by ErikSchierboom** [comment]
Go for it!

**Comment by misicnenad** [comment]
Here we goooo

**Pull request merged**
