### PR TITLE
Turn `lucians-luscious-lasagna` into a Concept Exercise + fix `low-power-embedded-game`

### LINKED ISSUE #148: Turn `lucians-luscious-lasagna` into a Concept Exercise
Towards #103 

You can basically copy/paste [Rust's metadata-related files](https://github.com/exercism/rust/tree/main/exercises/concept/lucians-luscious-lasagna) (introduction.md, instructions, hints etc.) and also copy/paste the [existing exercise implementation](https://github.com/exercism/cairo/tree/main/exercises/practice/lucians-luscious-lasagna).

In [_config.json_](https://exercism.org/docs/building/tracks/config-json#h-concept-exercises):
- mark the concept's status as "beta"
- mark that concepts being learned are `"functions"`

### PR DESCRIPTION
**Pull request by 0xNeshi**
Closes #148 

Also implemented `AbsImpl` to allow students to focus solely on tuples

### CODE REVIEW

**Comment by 0xNeshi** [comment]
@ErikSchierboom I am no longer able to merge my own nor other contributors' PRs, do you know what's going on?

**Review by BNAndras — APPROVED** [review]

**Comment by BNAndras** [comment]
My understanding is that while a track isn't launched, no reviews are needed before merging. On a live track, PRs should be reviewed by someone with write access besides the submitter before merging. So if Erik changed the merge settings, that'd make sense as to why you can't merge your own. That's pretty odd that you can't merge other PRs. If that just started occurring, it might be related to the work staff did in the last day to give @exercism/cross-track-maintainers write access to most of the track repos.

I'm a member of that team so I can wave your PRs through as needed.

**Comment by 0xNeshi** [comment]
@BNAndras

> On a live track, PRs should be reviewed by someone with write access besides the submitter before merging.

Ok, makes sense. But just 2 days ago I was able to merge my own PRs, see https://github.com/exercism/cairo/pull/139 and https://github.com/exercism/cairo/pull/144 :thinking: Maybe there _were_ recent changes to the merge settings.

> That's pretty odd that you can't merge other PRs.

Just tried it with https://github.com/exercism/cairo/pull/49 and was able to merge it _only if I previously explicitly approved it_. It might be faulty memory of mine, but I feel like I was able to merge other people's PRs without explicit approval.

**Comment by BNAndras** [comment]
Sounds about right if the staff weren't able to change those track settings before launch. So the issue at hand is that PR reviews are now required before merging, not that you can't merge a PR after a review was done, right? The former is expected behavior, but the latter might be indicative of a bug.

**Comment by 0xNeshi** [comment]
Exactly. I've been in contact with Exercism support, and they explained they'd like _all_ PRs to be reviewed _by someone_, even PRs from maintainers. The fact I was ever able to merge my own PRs on a live track was actually the problem :sweat_smile:

**Pull request merged**
